# Generated by Django 3.2.9 on 2021-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=500, unique=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
