# Generated by Django 3.2.9 on 2021-12-13 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cart_geeks_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='geeks_field',
            new_name='status',
        ),
    ]
